[MXCHIP] build for mxchip only

diff --git a/.github/workflows/build_packages.yaml b/.github/workflows/build_packages.yaml
--- a/.github/workflows/build_packages.yaml
+++ b/.github/workflows/build_packages.yaml
@@ -1,4 +1,4 @@
-name: Build packages
+name: Build packages for MXCHIP
 
 concurrency:
   group: build-${{ github.event_name }}-${{ github.ref }}
@@ -19,19 +19,19 @@ jobs:
       fail-fast: false
       matrix:
         arch:
-        - [amd64, gcc, g++, x86_64-linux-gnu, /usr/local]
-        - [arm64, aarch64-linux-gnu-gcc, aarch64-linux-gnu-g++, aarch64-linux-gnu, /usr/aarch64-linux-gnu]
-        - [mips, mips-linux-gnu-gcc, mips-linux-gnu-g++, mips-linux-gnu, /usr/mips-linux-gnu]
-        - [riscv64, riscv64-linux-gnu-gcc, riscv64-linux-gnu-g++, riscv64-linux-gnu, /usr/riscv64-linux-gnu]
+        # - [amd64, gcc, g++, x86_64-linux-gnu, /usr/local]
+        # - [arm64, aarch64-linux-gnu-gcc, aarch64-linux-gnu-g++, aarch64-linux-gnu, /usr/aarch64-linux-gnu]
+        # - [mips, mips-linux-gnu-gcc, mips-linux-gnu-g++, mips-linux-gnu, /usr/mips-linux-gnu]
+        # - [riscv64, riscv64-linux-gnu-gcc, riscv64-linux-gnu-g++, riscv64-linux-gnu, /usr/riscv64-linux-gnu]
         - [armhf, arm-linux-gnueabihf-gcc, arm-linux-gnueabihf-g++, arm-linux-gnueabihf, /usr/arm-linux-gnueabihf]
-        - [armel, arm-linux-gnueabi-gcc, arm-linux-gnueabi-g++, arm-linux-gnueabi, /usr/arm-linux-gnueabi]
+        # - [armel, arm-linux-gnueabi-gcc, arm-linux-gnueabi-g++, arm-linux-gnueabi, /usr/arm-linux-gnueabi]
         package_type:
-        - rpm
+        # - rpm
         - deb
         build_type:
-        - ""
-        - "-sqlite"
-        - "-msquic"
+        # - ""
+        # - "-sqlite"
+        # - "-msquic"
         - "-full"
         - "-full-debug"
         exclude:
@@ -216,98 +216,98 @@ jobs:
         token: ${{ github.token }}
         path: "build/_packages/nanomq*"
         ref: ${{ github.ref }}
-    - name: upload to aws s3
-      if: github.event_name == 'release'
-      run: |
-        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
-        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-        aws configure set default.region us-west-2
-        aws s3 cp --recursive build/_packages s3://packages.emqx/nanomq/$(git describe --abbrev=0 --tags)
+    # - name: upload to aws s3
+    #   if: github.event_name == 'release'
+    #   run: |
+    #     aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
+    #     aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+    #     aws configure set default.region us-west-2
+    #     aws s3 cp --recursive build/_packages s3://packages.emqx/nanomq/$(git describe --abbrev=0 --tags)
 
-  build_docker:
-    needs: [build_packages]
-    runs-on: ubuntu-20.04
+  # build_docker:
+  #   needs: [build_packages]
+  #   runs-on: ubuntu-20.04
 
-    strategy:
-      fail-fast: false
-      matrix:
-        suffix:
-        - ""
-        - "-slim"
-        - "-full"
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       suffix:
+  #       - ""
+  #       - "-slim"
+  #       - "-full"
 
-    steps:
-    - uses: actions/checkout@v3
-    - uses: actions/download-artifact@v3
-      with:
-        name: packages
-    - run: git submodule update --init --recursive
-    - run: docker build -t emqx/nanomq:$(git describe --tags --always)${{ matrix.suffix }} -f deploy/docker/Dockerfile${{ matrix.suffix }} .
-    - run: docker run -d -e DEBUG=1 --name nanomq $(docker images emqx/nanomq -q | head -1) --log_level debug
-    - name: test docker
-      run: |
-        set -e -x -u
-        sudo apt update && sudo apt install -y mosquitto-clients
-        ip_address=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' nanomq)
-        sleep 5
-        mosquitto_pub -h $ip_address -t 'topic/A' -m 'test'
-    - if: failure()
-      run: docker ps -a
-    - if: failure()
-      run: docker inspect nanomq
-    - if: failure()
-      run: docker logs nanomq
-    - uses: docker/setup-qemu-action@v2
-    - uses: docker/setup-buildx-action@v2
-    - uses: docker/metadata-action@v4
-      id: meta
-      with:
-        images: emqx/nanomq
-        flavor: |
-          latest=auto
-          suffix=${{ matrix.suffix }}
-        tags: |
-          type=ref,event=branch
-          type=ref,event=pr
-          type=ref,event=tag
-          type=semver,pattern={{version}}
-          type=semver,pattern={{major}}.{{minor}}
-    - uses: docker/login-action@v2
-      if: github.event_name == 'release'
-      with:
-        username: ${{ secrets.DOCKER_HUB_USER }}
-        password: ${{ secrets.DOCKER_HUB_TOKEN }}
-    - uses: docker/build-push-action@v3
-      if: github.event_name == 'release'
-      with:
-        platforms: linux/amd64,linux/arm64,linux/arm/v7
-        push: true
-        tags: ${{ steps.meta.outputs.tags }}
-        labels: ${{ steps.meta.outputs.labels }}
-        file: deploy/docker/Dockerfile${{ matrix.suffix }}
-        context: .
+  #   steps:
+  #   - uses: actions/checkout@v3
+  #   - uses: actions/download-artifact@v3
+  #     with:
+  #       name: packages
+  #   - run: git submodule update --init --recursive
+  #   - run: docker build -t emqx/nanomq:$(git describe --tags --always)${{ matrix.suffix }} -f deploy/docker/Dockerfile${{ matrix.suffix }} .
+  #   - run: docker run -d -e DEBUG=1 --name nanomq $(docker images emqx/nanomq -q | head -1) --log_level debug
+  #   - name: test docker
+  #     run: |
+  #       set -e -x -u
+  #       sudo apt update && sudo apt install -y mosquitto-clients
+  #       ip_address=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' nanomq)
+  #       sleep 5
+  #       mosquitto_pub -h $ip_address -t 'topic/A' -m 'test'
+  #   - if: failure()
+  #     run: docker ps -a
+  #   - if: failure()
+  #     run: docker inspect nanomq
+  #   - if: failure()
+  #     run: docker logs nanomq
+  #   - uses: docker/setup-qemu-action@v2
+  #   - uses: docker/setup-buildx-action@v2
+  #   - uses: docker/metadata-action@v4
+  #     id: meta
+  #     with:
+  #       images: emqx/nanomq
+  #       flavor: |
+  #         latest=auto
+  #         suffix=${{ matrix.suffix }}
+  #       tags: |
+  #         type=ref,event=branch
+  #         type=ref,event=pr
+  #         type=ref,event=tag
+  #         type=semver,pattern={{version}}
+  #         type=semver,pattern={{major}}.{{minor}}
+  #   - uses: docker/login-action@v2
+  #     if: github.event_name == 'release'
+  #     with:
+  #       username: ${{ secrets.DOCKER_HUB_USER }}
+  #       password: ${{ secrets.DOCKER_HUB_TOKEN }}
+  #   - uses: docker/build-push-action@v3
+  #     if: github.event_name == 'release'
+  #     with:
+  #       platforms: linux/amd64,linux/arm64,linux/arm/v7
+  #       push: true
+  #       tags: ${{ steps.meta.outputs.tags }}
+  #       labels: ${{ steps.meta.outputs.labels }}
+  #       file: deploy/docker/Dockerfile${{ matrix.suffix }}
+  #       context: .
 
-  publish_packages:
-    needs: [build_packages, build_docker]
-    runs-on: ubuntu-20.04
-    steps:
-    - name: update nanomq.io
-      if: github.event_name == 'release'
-      run: |
-        set -e -x -u
-        curl -w %{http_code} \
-             --insecure \
-             -H "Content-Type: application/json" \
-             -H "token: ${{ secrets.EMQX_IO_TOKEN }}" \
-             -X POST \
-             -d "{\"repo\":\"nanomq/nanomq\", \"tag\": \"${{ github.ref_name }}\" }" \
-             ${{ secrets.EMQX_IO_RELEASE_API }}
+  # publish_packages:
+  #   needs: [build_packages, build_docker]
+  #   runs-on: ubuntu-20.04
+  #   steps:
+  #   - name: update nanomq.io
+  #     if: github.event_name == 'release'
+  #     run: |
+  #       set -e -x -u
+  #       curl -w %{http_code} \
+  #            --insecure \
+  #            -H "Content-Type: application/json" \
+  #            -H "token: ${{ secrets.EMQX_IO_TOKEN }}" \
+  #            -X POST \
+  #            -d "{\"repo\":\"nanomq/nanomq\", \"tag\": \"${{ github.ref_name }}\" }" \
+  #            ${{ secrets.EMQX_IO_RELEASE_API }}
 
-    - uses: Swilder-M/push-packages@master
-      if: github.event_name == 'release'
-      env:
-        GIT_TOKEN: ${{ github.token }}
-        PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}
-      with:
-        product: nanomq
-        version: ${{ github.ref_name }}
+  #   - uses: Swilder-M/push-packages@master
+  #     if: github.event_name == 'release'
+  #     env:
+  #       GIT_TOKEN: ${{ github.token }}
+  #       PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}
+  #     with:
+  #       product: nanomq
+  #       version: ${{ github.ref_name }}
